-- schema.sql
CREATE DATABASE IF NOT EXISTS kampus_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kampus_db;

CREATE TABLE IF NOT EXISTS mahasiswa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  nim VARCHAR(20) NOT NULL UNIQUE,
  prodi VARCHAR(50) NOT NULL,
  angkatan INT NOT NULL,
  foto_path VARCHAR(255) DEFAULT NULL,
  status ENUM('aktif','nonaktif') NOT NULL DEFAULT 'aktif',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
